### PR TITLE
Handle catalog flag as well as properties flag

### PR DESCRIPTION
**Pull request by robmoore**
Addresses https://github.com/singer-io/tap-postgres/issues/54

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @robmoore, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by robmoore** [comment]
I can also add to the error message on line 698 so that it reads "No properties or catalog were selected", if desired.

**Comment by luandy64** [comment]
@robmoore If you can sign the  contribution license agreement, I'll work on reviewing this

**Comment by cmerrick** [comment]
You did it @robmoore!

Thank you for signing the Singer Contribution License Agreement.

**Comment by luandy64** [comment]
Thanks @robmoore! 👍

**Comment by robmoore** [comment]
Not sure what your release schedule is but I was hoping to be able to use this change via Pypi. Any ideas on when that might happen?

**Comment by luandy64** [comment]
It should be out now, sorry about that.

**Comment by robmoore** [comment]
No worries! Just wanted to know what to expect. Thanks for the quick turnaround.

**Pull request merged**
